#include <iostream>
using namespace std;

int main() {
	cout << "\x1" << endl;
	cout << "\x2" << endl;
	cout << "\x3" << endl;
	cout << "\x4" << endl;
	cout << "\x5 5" << endl;
	cout << "\x6" << endl;
	cout << "\x7" << endl;
	cout << "\x8" << endl;
	cout << "\x9" << endl;
	cout << "\x10 10" << endl;
	cout << "\x11" << endl;
	cout << "\x12" << endl;
	cout << "\x13" << endl;
	cout << "\x14" << endl;
	cout << "\x15 15" << endl;
	cout << "\x16" << endl;
	cout << "\x17" << endl;
	cout << "\x18" << endl;
	cout << "\x19" << endl;
	cout << "\x20 20" << endl;
	cout << "\x21" << endl;
	cout << "\x22" << endl;
	cout << "\x23" << endl;
	cout << "\x24" << endl;
	cout << "\x25 25" << endl;
	cout << "\x26" << endl;
	cout << "\x27" << endl;
	cout << "\x28" << endl;
	cout << "\x29" << endl;
	cout << "\x30 30" << endl;
	cout << "\x31" << endl;
	cout << "\x32" << endl;
	cout << "\x33" << endl;
	cout << "\x34" << endl;
	cout << "\x35 35" << endl;
	cout << "\x36" << endl;
	cout << "\x37" << endl;
	cout << "\x38" << endl;
	cout << "\x39" << endl;
	cout << "\x40 40" << endl;
	cout << "\x41" << endl;
	cout << "\x42" << endl;
	cout << "\x43" << endl;
	cout << "\x44" << endl;
	cout << "\x45 45" << endl;
	cout << "\x46" << endl;
	cout << "\x47" << endl;
	cout << "\x48" << endl;
	cout << "\x49" << endl;
	cout << "\x50 50" << endl;
	cout << "\x51" << endl;
	cout << "\x52" << endl;
	cout << "\x53" << endl;
	cout << "\x54" << endl;
	cout << "\x55 55" << endl;
	cout << "\x56" << endl;
	cout << "\x57" << endl;
	cout << "\x58" << endl;
	cout << "\x59" << endl;
	cout << "\x60 60" << endl;
	cout << "\x61" << endl;
	cout << "\x62" << endl;
	cout << "\x63" << endl;
	cout << "\x64" << endl;
	cout << "\x65 65" << endl;
	cout << "\x66" << endl;
	cout << "\x67" << endl;
	cout << "\x68" << endl;
	cout << "\x69" << endl;
	cout << "\x70 70" << endl;
	cout << "\x71" << endl;
	cout << "\x72" << endl;
	cout << "\x73" << endl;
	cout << "\x74" << endl;
	cout << "\x75 75" << endl;
	cout << "\x76" << endl;
	cout << "\x77" << endl;
	cout << "\x78" << endl;
	cout << "\x79" << endl;
	cout << "\x80 80" << endl;
	cout << "\x81" << endl;
	cout << "\x82" << endl;
	cout << "\x83" << endl;
	cout << "\x84" << endl;
	cout << "\x85 85" << endl;
	cout << "\x86" << endl;
	cout << "\x87" << endl;
	cout << "\x88" << endl;
	cout << "\x89" << endl;
	cout << "\x90 90" << endl;
	cout << "\x91" << endl;
	cout << "\x92" << endl;
	cout << "\x93" << endl;
	cout << "\x94" << endl;
	cout << "\x95 95" << endl;
	cout << "\x96" << endl;
	cout << "\x97" << endl;
	cout << "\x98" << endl;
	cout << "\x99 99";
}
